### ISSUE TITLE
cx_Freeze.freezer.ConfigError: no base named Win32GUI error on ubuntu 18.04 Lts

### ISSUE THREAD

**Issue by telegrambotdev** [pedrolemoz/MagicMagnet-Python#10]
while i executing

`python3 build_application.py build`  command i am getting  

`cx_Freeze.freezer.ConfigError: no base named Win32GUI error `

can you tell me how to fix this ?

**Comment by telegrambotdev** [comment]
and add a web ui support too

**Comment by pedrolemoz** [comment]
The `build_application.py` file aims to build a Windows binary. I have not built an binary for Linux, since Python is already installed in the system. Also, I didn't tested `cx_Freeze` in Linux.

I'm currently working in a better version of this project, in Dart using Flutter. I'll publish a mobile, desktop and web version soon.

**Comment by telegrambotdev** [comment]
> The `build_application.py` file aims to build a Windows binary. I have not built an binary for Linux, since Python is already installed in the system. Also, I didn't tested `cx_Freeze` in Linux.
> 
> I'm currently working in a better version of this project, in Dart using Flutter. I'll publish a mobile, desktop and web version soon.

yeah waiting for the web version
