### ISSUE TITLE
eta wen?

### ISSUE THREAD

**Issue by SmartBoy84** [pedrolemoz/MagicMagnet-Python#27]
https://user-images.githubusercontent.com/20285104/87355729-3d449780-c537-11ea-9d05-45c5ec2c2e5f.jpg

**Comment by pedrolemoz** [comment]
I'm actually refactoring this app. My goal is to get a material design like interface.

![Screenshot_1601824717](https://user-images.githubusercontent.com/20285104/95019487-fbaa2100-063b-11eb-9b67-4664706d055a.png)

![Screenshot_1601824713](https://user-images.githubusercontent.com/20285104/95019486-fa78f400-063b-11eb-8d1a-f5963101396e.png)

**Comment by pedrolemoz** [comment]
I built a new Windows version. You can try if you want. This version is a lot faster because of asynchounous async code and reactive programming.

[MagicMagnet](https://github.com/pedrolemoz/MagicMagnet-Python/files/5334034/MagicMagnet.Windows.zip)

![image](https://user-images.githubusercontent.com/20285104/95206389-07712100-07bd-11eb-8422-7767558a44d9.png)
